---
title: "Final Project"
author: "Naomi Giancola, Christina Sherpa & Tessa Finkelstein"
date: "December 20, 2019"
output:
  html_document:
    toc: true
    toc_depth: 2
    toc_float: true
    df_print: kable
---

<!--
Comments in HTML are like this! 
-->

# SECTION NAME

## Subsection name

Write an intro `index.html` page in blog-post style that summarizes your work. It should have

1. One visualization that best summarizes your work.
1. No more than 200 words of text

```{r setup, include=FALSE}
library(tidyverse)
library(gapminder)

library(readr)
UNdata_Export_20191209_200452883 <- read_csv("UNdata_Export_20191209_200452883.csv", 
    col_types = cols(Year = col_character()))
    
library(readr)
MH_12 <- read_csv("MH_12.csv", col_types = cols(`Age-standardized suicide rates (per 100 000 population)` = col_number(), 
    `Age-standardized suicide rates (per 100 000 population)_1` = col_number(), 
    `Age-standardized suicide rates (per 100 000 population)_2` = col_number(), 
    `Age-standardized suicide rates (per 100 000 population)_3` = col_number()))
```

```{r}
## Suicide (http://apps.who.int/gho/data/node.main.MHSUICIDEASDR?lang=en)

suicide_rates_per100000<-MH_12 %>% 
  rename(country= X1, sex= X2, "2016" ="Age-standardized suicide rates (per 100 000 population)", "2015" = "Age-standardized suicide rates (per 100 000 population)_1", "2010" = "Age-standardized suicide rates (per 100 000 population)_2", "2000" = "Age-standardized suicide rates (per 100 000 population)_3" ) 

suicide_rates_per100000 = suicide_rates_per100000[-1,]

tidy_suicide_rates_per100000 <- suicide_rates_per100000 %>% 
  pivot_longer(names_to = "year", 
               values_to = "rate", 
               cols = c("2000", "2010", "2015", 
                        "2016"))

## GDP (http://data.un.org/Data.aspx?d=SNAAMA&f=grID%3A101%3BcurrID%3AUSD%3BpcFlag%3A1)
UN_data<-UNdata_Export_20191209_200452883 %>% 
  rename(country = "Country or Area", year = "Year")

GDP_suicide <- tidy_suicide_rates_per100000 %>% 
  full_join(UN_data, by=c("year", "country"))

suicide_males <- suicide_with_continent %>% 
  filter(sex=="Male")

suicide_females <- suicide_with_continent %>% 
  filter(sex=="Female")

suicide_both <- suicide_with_continent %>% 
  filter(sex=="Both sexes")

suicide_2000 <- suicide_with_continent %>% 
  filter(year=="rate_2000")

suicide_2010 <- suicide_with_continent %>% 
  filter(year== "rate_2010")

suicide_2015 <- suicide_with_continent %>% 
  filter(year== "rate_2015")

suicide_2016 <- suicide_with_continent %>% 
  filter(year== "rate_2016")
```



```{r}
ggplot(data= suicide_with_continent, mapping= aes(x=gdpPercap, y= rate, color=continent))+
  geom_point()+
  facet_wrap(~year) 

ggplot(data= suicide_2000, mapping= aes(x=gdpPercap, y= rate, color=continent ))+
geom_point()+
facet_wrap(~sex)
  
```

```{r}
country_locations<-read_csv("https://github.com/albertyw/avenews/raw/master/old/data/average-latitude-longitude-countries.csv")

View(country_locations)

#join country_locations which has long and lat with tidy_suicide_rates_per100000

tidy_suicide_rates_per100000_locations <- tidy_suicide_rates_per100000 %>% 
  inner_join(country_locations, by = c("country" = "Country"))

tidy_suicide_rates_per100000_locations %>% 
  filter(year == "rate_2016" & sex == "Both sexes")

pal <- colorNumeric(
  palette = "Blues",
  domain = tidy_suicide_rates_per100000_locations$rate
)
 
leaflet(data = tidy_suicide_rates_per100000_locations) %>%
  addTiles() %>% 
  addMarkers(lat = ~Latitude, lng = ~Longitude , popup = ~country) %>% 
  addPolygons(data = tidy_suicide_rates_per100000_locations$rate,
  fillColor = ~pal(rate),
  weight = 2,
  opacity = 1,
  color = "black",
  fillOpacity = 0.7)

for_polygons<-world_map_sf %>% 
  inner_join(tidy_suicide_rates_per100000_locations, by = c("ID" = "country"))
#this party does not work yet sadly
for_polygons <- map(database = "world", plot = FALSE, fill = TRUE) %>% 
  st_as_sf(crs = 4326)
ggplot() +
  geom_sf(data = for_polygons) +
  theme_bw()+
  addPolygons(data = for_polygons,
  fillColor = ~pal(for_polygons$rate),
  weight = 2,
  opacity = 1,
  color = "black",
  fillOpacity = 0.7)
  
  ```

